### ISSUE TITLE
Teilnehmer anmelden

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#110]
Geht gerade nicht. Kann keine TN anmelden und bekomme auch keine Hinweise, dass evt. ein Feld nicht ausgefüllt wurde. Keine Anmeldebestätigung beim abschicken.

**Comment by bertoverflow** [comment]
Sollte jetzt gehen. Es sollte jetzt auch zumindest immer eine Erfolgs- oder Fehlermeldung geben, sodass man weiß dass sich zumindest etwas getan hat.
