### ISSUE TITLE
Alter des Kindes Anzeige Angebot

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#111]
wenn man ein Kind anmeldet, dass z.B. im April 10 Jahre alt wird, wird Angeln nicht angezeigt, da das Kind ja heute noch 9 ist oder bzw. bei der Anmeldung. Wenn das Angebot stattfindet, ist es aber 10 und es könnte also teilnehmen. Wir sollten also das Datum, ab dem die Altersbeschränkung gilt, auf das Ende der Sommerferien setzten. Dann sind evt. 3 oder 4 Kinder noch ein paar Tage jünger aber das ist hinzunehmen.

**Comment by bertoverflow** [comment]
Wir verwenden jetzt für die Berechnung des Alters immer das Alter des Kindes, welches es zum Beginn des Angebotes hat.
