### ISSUE TITLE
Parallele Veranstaltungen werden angezeigt

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#113]
Parallel stattfindende Veranstaltungen werden angezeigt und können auch angeklickt werden. Es kommt keine Fehlermeldung oder die andere wird nicht grau, wenn im gleichen Zeitraum zwei oder mehr Angebote gebucht werden.

**Comment by bertoverflow** [comment]
Wenn eine Veranstaltung ausgewählt ist, dann kann man sich damit überschneidende Veranstaltungen nun nicht mehr wählen.
