### ISSUE TITLE
pdf Veranstaltungen

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#16]
Veranstaltungen können nicht als pdf angezeigt werden.

**Comment by bertoverflow** [comment]
Genauer: Es wird ein PDF-Export pro Veranstaltung benötigt mit folgenden Infos:
* Liste aller Teilnehmer
* Name
* Alter / Geburtsdatum
* Telefonnummer für Notfälle
* Einschränkungen komplett
* Behinderung: ja/nein (individuelle Absprache mit Kinderbüro/Anbieter)
* Weitere Angaben: komplett
