### ISSUE TITLE
Stornieren der Projekte

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#23]
Beim bearbeiten der Teilnehmer kann man die Projekte nicht stornieren.

**Comment by mcguenther** [comment]
404 beim Versuch, Teilnehmer aus Projekt auszutragen.

REST-Endpunkt "/cancelproject" ist im Controller nicht deklariert. 
Außerdem besteht Verwechslungsgefahr mit bestehendem Endpunkt "/deleteProject", das ein gesamtes Projekt deaktiviert.  "/removeFromProject" wäre evtl vorzuziehen.
