### ISSUE TITLE
pdf Teilnehmer

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#24]
PDF der Teilnehmerdaten erstellen geht nicht

**Comment by jonashackt** [comment]
Siehe auch #16

**Comment by bertoverflow** [comment]
Das Erstellen eines PDFs für Teilnehmer ist nicht notwendig. Der entsprechende Button kann ausgebaut werden.

**Comment by bertoverflow** [comment]
Button entfernt.
