### ISSUE TITLE
Kein Projekt ausgewählt --> kein Senden möglich

### ISSUE THREAD

**Issue by jonashackt** [digital-bauhaus/Ferienpass#25]
Geschafft wird auch angezeigt, wenn man kein Projekt ausgewählt hat - denn das wird trotzdem gespeichert. Dabei sollte ein Teilnehmer ohne Projekt gar nicht erst gesendet werden könne.

**Comment by bertoverflow** [comment]
Dieser Fehler wird vom Backend abgefangen und dann auch entsprechender Dialog im Frontend angezeigt. Zwar erst nach dem Absenden, aber es wird kein Teilnehmer in der Datenbank angezeigt. Sollte so auch ok sein.
