### ISSUE TITLE
REST-API absichern gegen unauthorisierten Zugriff sowie Frontend ebenfalls absichern (inkl. Anbieten eines Logins)

### ISSUE THREAD

**Issue by jonashackt** [digital-bauhaus/Ferienpass#27]
(https://auth0.com/blog/vuejs2-authentication-tutorial/ nice to have)

Generell Admin-Login absichern

--> allow Origin only localhost und MS1

**Comment by grohmio** [comment]
Ist die backend REST API aktuell irgendwie abgesichert?

**Comment by jonashackt** [comment]
Prerequisite: https://github.com/digital-bauhaus/Ferienpass/issues/60
