### ISSUE TITLE
Mail-Adresse angebbar, wenn Projekt voll

### ISSUE THREAD

**Issue by jonashackt** [digital-bauhaus/Ferienpass#28]
Bei vollen Projekten, soll im Frontend ein Hinweis stehen, dass man sich per Email an den Ferienpass auf eine Warteliste setzen lassen kann

**Comment by bertoverflow** [comment]
Da zu diesem Thema noch zu viele Fragen offen sind, wurden die Tickets #17, #28, #30 in dem neuen Ticket #90 vereint.
