### ISSUE TITLE
Platzanzahl in Veranstaltungen + Warteliste 

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass#30]
Die Eltern sollen erkennen können, wie viele Plätze in einer Veranstaltung noch zur Verfügung stehen. Wenn eine Veranstalltung voll ist sollen die Eltern sich in eine Warteliste eintragen können. 

(verfügbare Plätze / Plätze insgesamt / [Wieviele haben sich auf die Warteliste gesetzt ? ] )

**Comment by bertoverflow** [comment]
Da zu diesem Thema noch zu viele Fragen offen sind, wurden die Tickets #17, #28, #30 in dem neuen Ticket #90 vereint.
