### ISSUE TITLE
Überschneidungen von Veranstalltungen (Nutzer)

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass#32]
Ich als **Nutzer** möchte bei der Anmeldung informiert werden ob sich die gewählte Veranstalltung mit bereits angemeldeten Veranstalltungen überschneidet.

**Comment by bertoverflow** [comment]
Die Angebote sind immer tageweise zu verstehen, d.h. wenn ein Angebot gewählt wurde, müssen alle anderen Angebote "deaktiviert" werden, die auch nur einen Tag Überschneidung mit diesem Angebot haben.

Mindestanforderung: Prüfung im Frontend und sofortiges Ausgrauen von Angeboten, die aufgrund der Überschneidung nicht mehr gewählt werden können
Wäre sicherlich gut: Prüfung nochmals im Backend

**Comment by bertoverflow** [comment]
Duplikat von #113 . Ist in der aktuellen Version behoben.
