### ISSUE TITLE
Invalide Tage bei Geburtsdatum führen zu Exception

### ISSUE THREAD

**Issue by NicolaiRuckel** [digital-bauhaus/Ferienpass#44]
Gibt man ein Datum ein, das nicht existiert, zum Beispiel 31. Februar, wirft das Backend eine Exception sobald auf Anmelden geklickt wird. Beim Frontend führt das dazu, dass es keine Rückmeldung auf den Klick gibt.

**Comment by bertoverflow** [comment]
Am sinnvollsten wäre es die 3 Einzelelemente im Anmeldeformular durch einen Datepicker (mit Textfeld als alternativer Eingabemöglichkeit) zu ersetzen

**Comment by bertoverflow** [comment]
Die Einzelfelder wurden durch einen Datepicker ersetzt. Es werden nun nur noch gültige Datumswerte generiert. Die generelle Fehlerbehandlung von Backend-Fehlern im Frontend wird in #119 umgesetzt.
