### ISSUE TITLE
Teilnehmerverwaltung im Admin-Bereich fehlerhaft

### ISSUE THREAD

**Issue by seeraeubert** [digital-bauhaus/Ferienpass#64]
- Stornierung von Projekten funktioniert nicht richtig (Teilnehmer werden scheinbar ausgetragen, aber die stornierten Projekte werden nicht angezeigt)
- TNs können mehrmals für Projekte angemeldet werden
- Keine Liste der TNs pro Projekt einsehbar

**Comment by seeraeubert** [comment]
- Die Teilnehmerverwaltung in den Projekten funktioniert jetzt. Es war nicht ganz klar, was ehemals mal für das "Stornieren" und "Reaktivieren" von Anmeldungen gedacht war. Aktuell ist die Umsetzung jetzt einfach so, dass das "reaktivieren" von "stornierten" Projekten einfach schlicht eine erneute Anmeldung für das Projekt bedeutet. Im Backend wird die Stornierung des Nutzers dann aus der entsprechenden Liste entfernt
- Bei den Projekten gibt es jetzt eine Liste mit den angemeldeten Teilnehmern

**Comment by jonashackt** [comment]
Sehr cool 💃
