### ISSUE TITLE
Textergänzung unter 4.  Angaben bei Behinderung

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#74]
Bitte direkt unter der Überschrift folgenden Text:

"Im Ferienpass sollen möglichst alle Kinder, egal ob mit oder ohne Behinderung, die Möglichkeit für tolle Ferien geboten bekommen. Leider sind nicht alle Angebote des Ferienpasses für alle Kinder mit körperlichen oder geistigen Einschränkungen geeignet. Sorgeberechtigte prüfen, ob das Angebot und die räumlichen Gegebenheiten den Fähigkeiten des Kindes entsprechen. Ein Elterngespräch zur Abklärung räumlicher Voraussetzung ist unbedingt zu empfehlen. 

Bitte kontaktieren Sie uns direkt, wenn Ihr Kind eine Begleitung benötigt und Sie dafür finanzielle Unterstützung beantragen möchten."

**Comment by bertoverflow** [comment]
Text eingefügt.
