### ISSUE TITLE
Checkbox Ermäßigungsberechtigung

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#76]
Checkbox einrichten: 
"Ich bin berechtig den ermäßigten Preis zu zahlen. Ich beziehe finanzielle Leistungen des Sozialamtes (Wohngeld, Kinderzuschlag, Bildung- und Teilhabe) oder des Jobcenters (ALG II, Harz IV)."

**Comment by bertoverflow** [comment]
Entsprechende Checkbox hinzugefügt.
