### ISSUE TITLE
Datumsanzeige Veranstaltung erstellen

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#78]
Beginn-Datum und End-Datum in der Anzeige (TT.MM.JJJ) berichtigen, sonst kann keine Veranstaltung erstellt werden.

**Comment by bertoverflow** [comment]
Beim Erstellen und Bearbeiten von Veranstaltungen kann jetzt das vorgegebene Datumsformat (TT.MM.JJJJ) verwendet werden. Falls das Datumsformat nicht erkannt wird, wird eine entsprechende Fehlermeldung angezeigt.
