### ISSUE TITLE
pdf exportieren

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#79]
die Daten können nicht als pdf exportiert werden. Wichtig, damit die Infos an alle Träger verschickt werden können.

**Comment by bertoverflow** [comment]
Genauer: Es wird ein PDF-Export pro Veranstaltung benötigt mit folgenden Infos:
* Liste aller Teilnehmer
* Name
* Alter / Geburtsdatum
* Telefonnummer für Notfälle
* Einschränkungen komplett
* Behinderung: ja/nein (individuelle Absprache mit Kinderbüro/Anbieter)
* Weitere Angaben: komplett

Ein PDF-Export für einen einzelnen Teilnehmer wird NICHT benötigt.

**Comment by bertoverflow** [comment]
Insgesamt Duplikat von #16 und #24
