### ISSUE TITLE
Anzeige Preis

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#80]
in Veranstaltung Anlegen kann die Angabe Preis weg

**Comment by bertoverflow** [comment]
Wie in #82 erläutert, ist die Preis/Kostenberechnung nicht vollends trivial, deswegen kann das entsprechende Feld im Frontend, Backend und der Datenbank erstmal ausgebaut werden.

**Comment by bertoverflow** [comment]
Preis wird jetzt nicht mehr angezeigt.
