### ISSUE TITLE
Textänderung Erklärung

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#97]
Folgende Texte aus dem Punkt 5 Erklärung streichen:

Wir bitten die Eltern bzw. Erziehungsberechtigten folgende Erklärung zu unterschreiben:

Die Anmeldung zu den Aktionen ist verbindlich. Bitte geben Sie dieses vierseitige Formular vollständig ausgefüllt und unterschrieben im Kinderbüro ab. Der ausstehende Betrag ist bei der Anmeldung im Kinderbüro Weimar zu entrichten. Daraufhin erhalten Sie einen Stempel im Ferienpass, der bei den Aktionen vorgezeigt werden muss.

Das Kinderbüro finden Sie im mon ami am Goetheplatz:
Kinderbüro Weimar, Goetheplatz, 99423 Weimar, Telefon: 0 36 43 / 49 49 90

**Comment by bertoverflow** [comment]
Text angepasst.
