### ISSUE TITLE
Textergänzung Stornierungsregelung

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#98]
Stornierungsregelung: Nach der Bezahlung entstehen Stornierungskosten. Bei Stornierung einer Aktion bis einer Woche vor der Veranstaltung werden 50% der Kosten berechnet. Ab einer Woche vor der Veranstaltung werden 100% berechnet. Die Stornierungskosten können umgangen werden, wenn ein anderes Kind für den freien Platz benannt wird.

ergänzen um einen Satz:
"Nehmen Sie für die Stornierung Kontakt mit uns auf: ferienpass@stadtweimar.de"

**Comment by bertoverflow** [comment]
Text angepasst.
